#############################################################################
# Makefile for building: sivia_simple
# Generated by qmake (2.01a) (Qt 4.6.2) on: Wed Feb 13 16:08:55 2013
# Project:  sivia_simple.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/lib64/qt4/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile sivia_simple.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -g -I/home23/pinheima/IBEX_PACK_LINUX64/INSTALL/IBEX/include/ibex -I/home23/pinheima/IBEX_PACK_LINUX64/INSTALL/soplex-1.7.0/src -I/home23/pinheima/IBEX_PACK_LINUX64/INSTALL/Profil-2.0.8/include -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -I/home23/pinheima/IBEX_PACK_LINUX64/INSTALL/IBEX/include/ibex -I/home23/pinheima/IBEX_PACK_LINUX64/INSTALL/soplex-1.7.0/src -I/home23/pinheima/IBEX_PACK_LINUX64/INSTALL/Profil-2.0.8/include -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)   -L/home23/pinheima/IBEX_PACK_LINUX64/INSTALL/IBEX/lib -L/home23/pinheima/IBEX_PACK_LINUX64/INSTALL/soplex-1.7.0/lib -L/home23/pinheima/IBEX_PACK_LINUX64/INSTALL/Profil-2.0.8/lib -libex -lsoplex -lProfil -lBias -llr -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		sivia.cpp \
		frame.cpp \
		DrawV.cpp \
		simu.cpp \
		drawf.cpp \
		drawsolve.cpp moc_mainwindow.cpp \
		moc_frame.cpp
OBJECTS       = main.o \
		mainwindow.o \
		sivia.o \
		frame.o \
		DrawV.o \
		simu.o \
		drawf.o \
		drawsolve.o \
		moc_mainwindow.o \
		moc_frame.o
DIST          = /usr/lib64/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/debug.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		sivia_simple.pro
QMAKE_TARGET  = sivia_simple
DESTDIR       = 
TARGET        = sivia_simple

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: sivia_simple.pro  /usr/lib64/qt4/mkspecs/linux-g++-64/qmake.conf /usr/lib64/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/debug.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/lib64/qt4/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile sivia_simple.pro
/usr/lib64/qt4/mkspecs/common/g++-multilib.conf:
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/debug.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/lib64/qt4/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile sivia_simple.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/sivia_simple1.0.0 || $(MKDIR) .tmp/sivia_simple1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/sivia_simple1.0.0/ && $(COPY_FILE) --parents mainwindow.h frame.h sivia.h drawv.h simu.h drawf.h drawsolve.h .tmp/sivia_simple1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp sivia.cpp frame.cpp DrawV.cpp simu.cpp drawf.cpp drawsolve.cpp .tmp/sivia_simple1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/sivia_simple1.0.0/ && (cd `dirname .tmp/sivia_simple1.0.0` && $(TAR) sivia_simple1.0.0.tar sivia_simple1.0.0 && $(COMPRESS) sivia_simple1.0.0.tar) && $(MOVE) `dirname .tmp/sivia_simple1.0.0`/sivia_simple1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/sivia_simple1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_frame.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_frame.cpp
moc_mainwindow.cpp: frame.h \
		mainwindow.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_frame.cpp: frame.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) frame.h -o moc_frame.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib64/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		frame.h \
		ui_mainwindow.h \
		sivia.h \
		drawv.h \
		simu.h \
		drawf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

sivia.o: sivia.cpp sivia.h \
		frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sivia.o sivia.cpp

frame.o: frame.cpp frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frame.o frame.cpp

DrawV.o: DrawV.cpp drawv.h \
		frame.h \
		sivia.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DrawV.o DrawV.cpp

simu.o: simu.cpp simu.h \
		frame.h \
		sivia.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simu.o simu.cpp

drawf.o: drawf.cpp drawf.h \
		frame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawf.o drawf.cpp

drawsolve.o: drawsolve.cpp drawsolve.h \
		frame.h \
		sivia.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawsolve.o drawsolve.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_frame.o: moc_frame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frame.o moc_frame.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

